fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: "%mailer_email%"
        sender_name: "%mailer_name%"
    resetting:
        email:
            template:   '@FOSUser/Resetting/email.txt.twig'
#    registration:
#        email:
#            template:   '@FOSUser/Registration/email.txt.twig'